insert into servers (server_id, url, user_id, port, local_dome_user, local_dome_user_password, dome_user_space)
	values (3, 'localhost', 111, 7795, 'ceed', 'ceed', 'USER'); 

insert into service (service_id, organization_id, title, owner_id)
	values (2,1,'Alpha service', 111);
	


insert into service_interface (version, model_id, interface_id_str, type, name, service_id, server_id)
	values (1, 'aff647da-d82f-1004-8e7b-5de38b2eeb0f', 'aff647db-d82f-1004-8e7b-5de38b2eeb0f', 'interface',
		'Default Interface', 3,3);

insert into service_interface_path values (2,30);
		
insert into service_specifications (id, service_id, input, ouput) values (1, 3, 2, 1);

insert into service_interface_parameter (parameter_id, interface_id, name, type, unit, category, default_value, parameter_id_txt, parameter_position, input_parameter)
	values (1, 2, 'SpecimenWidth', 'Real', 'meter', 'length', 3, 'd9f30f3a-d800-1004-8f53-704dbfababa8', 1, true);
insert into service_interface_parameter (parameter_id, interface_id, name, type, unit, category, default_value, parameter_id_txt, parameter_position, input_parameter)
	values (2, 2, 'CrackLength', 'Real', 'meter', 'length', 1, 'd9f30f37-d800-1004-8f53-704dbfababa8', 2, true);
insert into service_interface_parameter (parameter_id, interface_id, name, type, unit, category, default_value, parameter_id_txt, parameter_position, input_parameter, instancename)
	values (3, 2, 'Alpha', 'Real', 'no unit', 'no unit', 0.3333333333333333, 'd9f30f37-d800-1004-8f53-704dbfababa8', 3, false,'Alpha');